### PR TITLE
Remove blurb about recurring events

### PR DESCRIPTION
**Pull request by benblankley**
Let them speak for themselves.

### CODE REVIEW

**Comment by jcbwlkr** [comment]
Delete more please 😀 the recurring events heading and the docs that follow. Basically everything before the meetup logo

**Comment by chrisl8** [comment]
But if you accept this request @jcbwlkr and let him make another pull request to delete more, then he can have enough PRs for a shirt! :)

**Comment by jcbwlkr** [comment]
haha I'm sure Ben can come up with another legitimate PR =P

**Comment by benblankley** [comment]
Okay, how about that?

**Comment by jcbwlkr** [comment]
That's the ticket! Thanks

**Pull request merged**
